### ISSUE TITLE
fix redirect?

### ISSUE THREAD

**Issue by odinuv** [keboola/data-loader#35]
Not allowing login redirect to '/notebooks/notebook.ipynb?

in PT logs, or get rid of the redirect completely?https://keboolaglobal.slack.com/archives/CGCKT849E/p1556177663152000?thread_ts=1556115882.139000&cid=CGCKT849E

**Comment by pivnicek** [comment]
Not sure I totally understand the issue, but how about as a config param?  I imagine in the future they will choose notebook as a config param anyways?

**Comment by odinuv** [comment]
personally i'd like to avoid new config params for as long as possible, it's enough complicated already

**Comment by odinuv** [comment]
obsolete
