### ISSUE TITLE
Storing file >4GB to S3 yields app error

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/data-loader#5]
Should use multipart upload

**Comment by Halama** [comment]
a není to nakonec na sapi klienta?

**Comment by Halama** [comment]
tahle komponenta dělá input mapping ne?

**Comment by ondrejhlavacek** [comment]
Na klienta to nakonec bude, ale dataloader jsem vyčetl ze stack tracu

![image](https://cloud.githubusercontent.com/assets/497675/25423309/7b9701b0-2a64-11e7-9763-00fc7840d4e1.png)

**Comment by ondrejhlavacek** [comment]
Jestli von to nebude jinej DataLoader!

**Comment by Halama** [comment]
rekl bych ze jo https://github.com/keboola/docker-bundle/blob/d264d1491b21517a261e6061d1b9de0750f771d5/Docker/Runner/DataLoader.php

**Comment by ondrejhlavacek** [comment]
Jasně no, teď na to koukam :-) Achjo!
